version: '3.7'

services:
  postgres_data0:
    hostname: postgres0
    container_name: postgres0
    image: postgres:16
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data0:/data/db'
    restart: always
volumes:
  postgres_data0:
    external: true
