version: '3.8'

services:
  postgres_data0:
    hostname: postgres0
    container_name: postgres0
    image: postgres:16
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data0:/data/db'
    restart: always
  redis0:
    image: 'redis:7.2.3-bookworm'
    container_name: redis0
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data0:/bitnami/redis0/data'
volumes:
  postgres_data0:
    external: true
  redis_data0:
    driver: local
